version: "3.7"
volumes:
    db-store:
    php-fpm-socket:
services:
    https-portal:
        container_name: twitter-https
        image: steveltn/https-portal:1
        ports:
            - '81:81'
            - '443:443'
        environment:
            STAGE: local
            DOMAINS: "localhost -> http://web"
        volumes:
            - ./docker/https-portal/cert:/var/lib/https-portal
        depends_on:
            - web

    app:
        container_name: twitter-app
        build: ./docker/php
        volumes:
            - php-fpm-socket:/var/run/php-fpm
            - .:/opt/laravel-twitter

    web:
        container_name: twitter-web
        build: ./docker/nginx
        volumes:
            - php-fpm-socket:/var/run/php-fpm
            - .:/opt/laravel-twitter

    db:
        container_name: twitter-db
        build: ./docker/mysql
        volumes:
            - db-store:/var/lib/mysql
            - ./docker/logs:/var/log/mysql
        ports:
            - 3306:3306

    node:
        container_name: twitter-node
        image: node:14.2-buster
        working_dir: "/opt/laravel-twitter"
        command: /bin/bash -c 'npm i && npm rebuild node-sass && npm run watch'
        volumes:
            - .:/opt/laravel-twitter
        environment:
            TZ: Asia/Tokyo
