name: before_check
on: pull_request
jobs:
  # 構文チェック
  lint:
    # From here: https://github:com/actions/virtual-environments
    runs-on: ubuntu-18.04
    steps:
      # From here: https://github.com/actions/checkout
      - uses: actions/checkout@v2
        with:
          # 全てのブランチを取得する
          fetch-depth: 0
          # From here: https://github.com/reviewdog/reviewdog
          ref: ${{ github.event.pull_request.head.ref }}
      # git diff name-onlyを環境変数に代入
      # From here https://github.com/technote-space/get-diff-action
      - uses: technote-space/get-diff-action@v6
      - run: echo ${{ env.GIT_DIFF }}
      - name: set git user
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
      - uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest
      - name: setup php 8.1
        run: sudo update-alternatives --set php /usr/bin/php8.1
        # From here: https://github.com/squizlabs/PHP_CodeSniffer

      - name: set php-version
        run: ./vendor/bin/phpcs --config-set php_version 70234
      - name: phpcbf & commit
        run: |
          ./vendor/bin/phpcbf --standard=phpcbf.xml --extensions=php ${{ env.GIT_DIFF }} || git add ${{ env.GIT_DIFF }}
          git commit -m "fixed by phpcbf" || echo "No changes to commit"
          git push || echo "No commit to push"

  # 静的解析
  analyze:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: reviewdog/action-setup@v1
        with:
          reviewdog_version: latest
      - name: setup php 8.1
        run: sudo update-alternatives --set php /usr/bin/php8.1
        # From here: https://github.com/phpstan/phpstan
      - name: analyze
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: git diff --name-only origin/${{ github.base_ref }} HEAD | xargs -IXXX ./vendor/bin/phpstan analyze XXX --error-format=raw -c phpstan.neon | reviewdog -name="phpstan" -f=phpstan -diff="git diff origin/${{ github.base_ref }} HEAD" -reporter=github-pr-review
